create products components
GSG-G10/gifty pull request #48
Opened 2021-10-04 21:45 UTC by Ahmad-Omar

2021-10-04 21:59 UTC, umarsalah approved these changes

2021-10-05 04:27 UTC, ameera-abed approved these changes

2021-10-05 09:34 UTC, Raghad-Mezied approved these changes

2021-10-05 10:49 UTC, Raghad-Mezied submitted a review, later dismissed

2021-10-05 10:51 UTC, umarsalah approved these changes

2021-10-05 11:32 UTC, LinaYahya requested changes
Good work Ahmad, 
Try to fix eslint errors, and validate your props!

2021-10-05 11:32 UTC, LinaYahya commented on client/package.json
> +    "@emotion/styled": "^11.3.0",
packages already listed in package json

2021-10-05 11:32 UTC, LinaYahya commented on client/src/components/ProductsContainer/index.jsx
> +      <Pagination
maybe you need to render it conditionally when products more than six,
also, try to list 15 products, see what will happen?!

2021-10-05 11:32 UTC, LinaYahya commented on client/src/components/ProductsContainer/ProductCard/index.jsx
> +        alt="sss"
`alt` should be descriptive

2021-10-05 12:24 UTC, Ahmad-Omar commented on client/package.json
> +    "@emotion/styled": "^11.3.0",
I don't see them!

2021-10-05 13:20 UTC, Raghad-Mezied submitted a review, later dismissed

2021-10-05 13:21 UTC, umarsalah approved these changes

2021-10-05 14:02 UTC, Raghad-Mezied approved these changes

2021-10-05 14:09 UTC, umarsalah approved these changes

2021-10-05 14:33 UTC, ameera-abed approved these changes

2021-10-06 09:20 UTC, LinaYahya approved these changes

2021-10-06 10:57 UTC, merged