Create add product route
GSG-G10/gifty pull request #50
Opened 2021-10-05 10:06 UTC by umarsalah

2021-10-05 10:24 UTC, ameera-abed approved these changes, later dismissed

2021-10-05 10:55 UTC, Raghad-Mezied submitted a review, later dismissed

2021-10-05 10:56 UTC, Ahmad-Omar approved these changes, later dismissed

2021-10-05 11:51 UTC, LinaYahya requested changes

2021-10-05 11:51 UTC, LinaYahya commented on server/controllers/addProduct.js
> +    res.json({ msg: 'You are not a seller' });
specify status here

2021-10-05 11:51 UTC, LinaYahya commented on server/controllers/addUser.js
> +  } = signupSchema.validate(req.body);
try to validate your body asynchronously, also if you want validation to continue even If your first validator failed, add `{abortEarly: false}` as options to your validate

2021-10-05 11:51 UTC, LinaYahya commented on server/controllers/addUser.js
> +      .then((hashed) => addUserQuery(username, email, hashed, userRole)
Not sure why you did those changes in addProduct branch, 
Even though did you think what might happen if you try to add a new user with an existing email?!

2021-10-05 11:51 UTC, LinaYahya commented on server/controllers/addUser.js
>                .then(({ rows }) => {
avoid nested promise

2021-10-05 11:51 UTC, LinaYahya commented on server/controllers/addProduct.js
> +    addProductQuery(name, catagory, price, description, img)
validation goes first

2021-10-05 13:20 UTC, Ahmad-Omar approved these changes, later dismissed

2021-10-05 13:20 UTC, Raghad-Mezied submitted a review, later dismissed

2021-10-05 14:09 UTC, Ahmad-Omar approved these changes

2021-10-05 14:33 UTC, ameera-abed approved these changes

2021-10-06 09:12 UTC, Raghad-Mezied approved these changes

2021-10-06 09:33 UTC, LinaYahya requested changes

2021-10-26 13:50 UTC, closed without merging